baseURL = 'https://wica.davsk.net/'
languageCode = 'en-us'
title = 'Wealthy Innovations'
theme = ["github.com/theNewDynamic/gohugo-theme-ananke"]

DefaultContentLanguage = "en"
SectionPagesMenu = "main"
Paginate = 6 # this is set low for demonstrating with dummy content. Set to a higher number
googleAnalytics = ""
enableRobotsTXT = true

sectionPagesMenu = "main"

[languages]
  [languages.en]
    title = "Homepage"
    weight = 1
    contentDir = "content/en"
    # languageDirection = 'rtl' for Right-To-Left languages
  [languages.fr]
    title = "page d'accueil"
    weight = 2
    contentDir = "content/fr"

[sitemap]
  changefreq = "monthly"
  priority = 0.5
  filename = "sitemap.xml"

[params]
  text_color = ""
  author = "Filmon"
  favicon = ""
  site_logo = ""
  description = "Independent research a world of planning option."
  # choose a background color from any on this page: https://tachyons.io/docs/themes/skins/ and preface it with "bg-"
  background_color_class = "bg-black"
  recent_posts_number = 6

[[params.ananke_socials]]
name = "twitter"
url = "https://twitter.com/GoHugoIO"
